source = ~/.cache/wal/colors-hyprland.css

background {
    monitor =
    path = screenshot
    blur_passes = 1
}

input-field {
    monitor =
    size = 250, 60
    outline_thickness = 2
    dots_size = 0.2
    dots_spacing = 0.35
    dots_center = true
    outer_color = rgba(0, 0, 0, 0)
    inner_color = rgba(0, 0, 0, 0.2)
    font_color = $color4
    fade_on_empty = false
    check_color = rgb(204, 136, 34)
    placeholder_text = Password...
    font_family = JetBrainsMono Nerd Font
    position = 0, -200
}

# date
label {
  monitor =
  text = cmd[update:1000] echo "$(date +"%A, %B %d, %Y")"
  color = $color4
  font_size = 22
  font_family = JetBrainsMono Nerd Font
  position = 0, 300
}

# time
label {
  text = $TIME12
  color = $color4
  font_size = 95
  font_family = JetBrainsMono Nerd Font
  position = 0, 200
}
